#include<iostream.h>
#include<conio.h>
#include<stdio.h>
void main()
{
clrscr();
int a,b,c,d;
cout<<"Masukann NIlai A :";cin>>a;
cout<<"Masukann NIlai B :";cin>>a;
cout<<"Masukann NIlai C :";cin>>a;
cout<<"Masukann NIlai D :";cin>>a;

a*=5; //a=a*5
b/=5; //b=b/5                                                                                  
c%=5; //c=c%5
d+=5; //d=d+5

cout<<"Hasil dari a*=5="<<a<<endl;
cout<<"Hasil dari b/=5="<<a<<endl;
cout<<"Hasil dari c%=5="<<a<<endl;
cout<<"Hasil dari d+=5="<<a<<endl;
getch();

}
